# Generated by Django 5.2.3 on 2026-07-01 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('plots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='customers.customer')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='plots.plot')),
                ('reserved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reservation_date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('reservation', 'Reservation'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled'), ('transferred', 'Transferred')], default='reservation', max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('installment_months', models.IntegerField(default=60)),
                ('monthly_installment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grace_period_days', models.IntegerField(default=0)),
                ('penalty_rate', models.DecimalField(decimal_places=2, default=0, help_text='Daily penalty rate (%)', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('reservation_date', models.DateField(blank=True, null=True)),
                ('reservation_expiry', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customers.customer')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='plots.plot')),
                ('sales_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='sales.sale')),
            ],
            options={
                'ordering': ['sale', 'installment_number'],
            },
        ),
    ]
