# Generated by Django 5.2.3 on 2026-07-02 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_installmentschedule_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
