# Generated by Django 5.2.3 on 2026-07-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_reservation_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform commission for this sale', max_digits=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='commission_paid',
            field=models.BooleanField(default=False),
        ),
    ]
