services:
  - type: web
    name: prime-land-ltd
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn land_selling.wsgi --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "prime-land-ltd.onrender.com,.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://prime-land-ltd.onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.5"
