# Generated by Django 5.2.3 on 2026-07-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('replaced', 'Replaced')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('customer', 'Customer Only'), ('staff', 'Staff Only'), ('both', 'Customer & Staff')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('sale_agreement', 'Sale Agreement'), ('booking_form', 'Booking Form'), ('payment_receipt', 'Payment Receipt'), ('payment_statement', 'Payment Statement'), ('survey_map', 'Survey Map'), ('beacon_certificate', 'Beacon Certificate'), ('transfer_form', 'Transfer Form'), ('title_deed', 'Title Deed'), ('id_document', 'Identification Document'), ('passport_photo', 'Passport Photo'), ('proof_of_payment', 'Proof of Payment'), ('completion_certificate', 'Completion Certificate'), ('project_brochure', 'Project Brochure'), ('company_document', 'Company Document'), ('other', 'Other')], max_length=30),
        ),
    ]
