# Generated by Django 5.2.3 on 2026-07-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform commission % per sale (for percentage plans)', max_digits=5),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('fixed', 'Fixed Monthly Fee'), ('percentage', 'Percentage of Sales')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly price (for fixed plans)', max_digits=10),
        ),
    ]
