# Generated by Django 5.2.3 on 2026-07-01 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=50)),
                ('size_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=20, help_text='Percentage required as deposit', max_digits=5)),
                ('max_installment_months', models.IntegerField(default=60)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual interest rate for installments (%)', max_digits=5)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('coordinates', models.CharField(blank=True, help_text='Google Maps coordinates', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='projects.amenity')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to='projects.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'plot_number'],
                'unique_together': {('project', 'plot_number')},
            },
        ),
        migrations.CreateModel(
            name='PlotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plots/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plots.plot')),
            ],
        ),
    ]
