# Generated by Django 5.2.3 on 2026-07-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Prime Lands Ltd', max_length=200)),
                ('tagline', models.CharField(default='Your Trusted Real Estate Partner', max_length=200)),
                ('email', models.EmailField(default='info@primelands.com', max_length=254)),
                ('phone', models.CharField(default='+254 700 000 000', max_length=20)),
                ('address', models.TextField(default='99 Westlands Rd, Nairobi, Kenya')),
                ('logo', models.ImageField(blank=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, upload_to='settings/')),
                ('google_maps_api_key', models.CharField(blank=True, max_length=200)),
                ('about_text', models.TextField(blank=True)),
                ('mission_text', models.TextField(blank=True)),
                ('vision_text', models.TextField(blank=True)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_twitter', models.URLField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('social_linkedin', models.URLField(blank=True)),
                ('deposit_percentage_default', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('installment_months_default', models.IntegerField(default=60)),
                ('interest_rate_default', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('receipt_prefix', models.CharField(default='RCP', max_length=10)),
                ('currency_symbol', models.CharField(default='KSh', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Setting',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('about', 'About Us'), ('faq', 'FAQs'), ('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy'), ('hire_purchase', 'Hire Purchase')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
