# Generated by Django 5.2.3 on 2026-07-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='mpesa_callback_url',
            field=models.CharField(blank=True, default='https://9cc3-102-205-50-218.ngrok-free.app/payments/mpesa/callback/', help_text='Public URL for M-Pesa STK Push callback', max_length=500),
        ),
    ]
