# Generated by Django 5.2.3 on 2026-07-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_companysetting_mpesa_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Platform commission percentage on each sale', max_digits=5),
        ),
    ]
